# Generated by Django 3.0.3 on 2020-02-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(default=0)),
                ('game_on', models.BooleanField(default=False)),
                ('num_players', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=6)),
                ('in_game', models.BooleanField(default=False)),
                ('total_balance', models.IntegerField(default=0)),
                ('in_game_chips', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Poker_app.Game')),
            ],
        ),
    ]
